version: "3.8"
services:
    crm-app-php:
        build:
            context: .
        volumes:
            - .:/var/www/html/
        ports:
            - "8081:80"
        environment:
            PHP_POOL_NAME: "app-php"

#    crm-app-task:
#        image: serversideup/php:8.2-cli
#        command: ["su", "webuser", "-c", "php artisan schedule:work"]
#        volumes:
#            - .:/var/www/html/
#
#    crm-app-queue-1:
#        image: serversideup/php:8.2-cli
#        command: ["su", "webuser", "-c", "php artisan queue:work"]
#        volumes:
#            - .:/var/www/html/
#
#    crm-app-queue-2:
#        image: serversideup/php:8.2-cli
#        command: ["su", "webuser", "-c", "php artisan queue:work"]
#        volumes:
#            - .:/var/www/html/
